/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import data.Persistencia;
import domain.Sucursal;
import domain.Vehiculo;
import domain.VehiculoCombustible;
import domain.VehiculoElectrico;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author ferna
 */
public class CargarVehiculoView extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCargarVehiculo
     */
    public CargarVehiculoView() {
        initComponents();
        if (data.Persistencia.getSucursales().isEmpty()) {
        data.Persistencia.inicializar();
    }
        
    comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELÉCTRICO", "COMBUSTIBLE" }));
    
    comboBoxMarca.removeAllItems();
    comboBoxMarca.addItem("Renault");
    comboBoxMarca.addItem("Ford");
    comboBoxMarca.addItem("Iveco");
    comboBoxMarca.addItem("Mercedes");
    comboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel());
    
    for (domain.Sucursal s : data.Persistencia.getSucursales()) {
        ((javax.swing.DefaultComboBoxModel)comboBoxSucursal.getModel()).addElement(s);
    }
        
        comboBoxMarca.addItem("Renault");
        comboBoxMarca.addItem("Ford");
        comboBoxMarca.addItem("Iveco");
        comboBoxMarca.addItem("Mercedes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TextFieldPatente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxMarca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TextFieldModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldAnio = new javax.swing.JTextField();
        comboBoxSucursal = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextFieldCapacidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextFieldKmbase = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextFieldKmLitro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextFieldLitrosExtra = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(51, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("GUARDAR VEHICULO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("TIPO DE VEHICULO");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1", "item 2 ", "item 3" }));
        comboBoxTipo.setToolTipText("");
        comboBoxTipo.setActionCommand("comboBoxTipo");
        comboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoActionPerformed(evt);
            }
        });

        jLabel2.setText("PATENTE");

        TextFieldPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPatenteActionPerformed(evt);
            }
        });

        jLabel3.setText("MARCA");

        comboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMarcaActionPerformed(evt);
            }
        });

        jLabel4.setText("MODELO");

        jLabel5.setText("AÑO");

        comboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("SUCURSAL");

        jLabel7.setText("CAPACIDAD DE CARGA");

        jLabel8.setText("kWh Base");

        TextFieldKmbase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldKmbaseActionPerformed(evt);
            }
        });

        jLabel9.setText("Km/Litro");

        TextFieldKmLitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldKmLitroActionPerformed(evt);
            }
        });

        jLabel10.setText("Litros Extra");

        TextFieldLitrosExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldLitrosExtraActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldPatente)
                    .addComponent(comboBoxTipo, 0, 121, Short.MAX_VALUE)
                    .addComponent(comboBoxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldModelo)
                    .addComponent(TextFieldAnio)
                    .addComponent(TextFieldCapacidad))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldKmbase)
                    .addComponent(TextFieldKmLitro)
                    .addComponent(TextFieldLitrosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextFieldPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(comboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(TextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(TextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(comboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addComponent(jLabel7))
                            .addComponent(TextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldKmbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldKmLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TextFieldLitrosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMarcaActionPerformed

    private void TextFieldPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPatenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPatenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoActionPerformed
       String tipo = comboBoxTipo.getSelectedItem().toString();

    if (tipo.equals("ELÉCTRICO")) {
   
        TextFieldKmbase.setEnabled(true);
        TextFieldKmLitro.setEnabled(false);
        TextFieldLitrosExtra.setEnabled(false);
        TextFieldKmLitro.setText("");
        TextFieldLitrosExtra.setText("");
    } else {
        TextFieldKmbase.setEnabled(false);
        TextFieldKmbase.setText("");
        TextFieldKmLitro.setEnabled(true);
        TextFieldLitrosExtra.setEnabled(true);
    }
    }//GEN-LAST:event_comboBoxTipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
     
            String patente = TextFieldPatente.getText().trim();
            String marca = comboBoxMarca.getSelectedItem().toString();
            String modelo = TextFieldModelo.getText().trim();

         
            int anio = Integer.parseInt(TextFieldAnio.getText());
            double capacidad = Double.parseDouble(TextFieldCapacidad.getText());

         
            Sucursal sucursal = (Sucursal) comboBoxSucursal.getSelectedItem();
            Vehiculo nuevoVehiculo = null;

            String tipoStr = comboBoxTipo.getSelectedItem().toString();
            if (tipoStr.equals("ELÉCTRICO")) {
              
                double kwhBase = Double.parseDouble(TextFieldKmbase.getText());
                nuevoVehiculo = new VehiculoElectrico(patente, marca, modelo, anio, capacidad, sucursal, kwhBase);

            } else {

                double kmLitro = Double.parseDouble(TextFieldKmLitro.getText());
                double litrosExtra = Double.parseDouble(TextFieldLitrosExtra.getText());

            
                nuevoVehiculo = new VehiculoCombustible(patente, marca, modelo, anio, capacidad, sucursal, kmLitro, litrosExtra);
            }

          
            if (nuevoVehiculo != null) {
                Persistencia.getVehiculos().add(nuevoVehiculo);

                JOptionPane.showMessageDialog(this, "¡Vehículo registrado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Verifique que Año, Capacidad y Consumo sean números válidos.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextFieldKmbaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldKmbaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldKmbaseActionPerformed

    private void TextFieldLitrosExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldLitrosExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldLitrosExtraActionPerformed

    private void TextFieldKmLitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldKmLitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldKmLitroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarVehiculoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldAnio;
    private javax.swing.JTextField TextFieldCapacidad;
    private javax.swing.JTextField TextFieldKmLitro;
    private javax.swing.JTextField TextFieldKmbase;
    private javax.swing.JTextField TextFieldLitrosExtra;
    private javax.swing.JTextField TextFieldModelo;
    private javax.swing.JTextField TextFieldPatente;
    private javax.swing.JComboBox<String> comboBoxMarca;
    private javax.swing.JComboBox<String> comboBoxSucursal;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
